### PR TITLE
Add connection to newest version of MongoClient

### PR DESCRIPTION
**Pull request by ItaloGoncales**
Hey singingfish,

I'm using the Catalyst::Model::MongoDB and I was needed to change your code for connect with the newest version of MongoClient module.

Seems that the new version does not support the method 'authenticate' anymore, but the 'connect' method instead.

I hope you accept my modifications, so we all will acan use your module on Catalyst!

Cheers,

Italo Gonçales

### CODE REVIEW

**Comment by dr-kd** [comment]
do you have a cpan id?  I can give you comaint.

**Comment by ItaloGoncales** [comment]
Yes I have, it's GONCALES

**Comment by dr-kd** [comment]
you have comaint on the module and contributor status on this repo :)

**Comment by ItaloGoncales** [comment]
Thank you!

**Pull request merged**
